# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param simulator.modelsimInstallPath D:/modelsim_2020.4/win64
set_param xicom.use_bs_reader 1
set_param labtools.auto_update_hardware 0
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.cache/wt [current_project]
set_property parent.project_path E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/new/flash_read_ctrl.v
  E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/new/key_filter.v
  E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/new/uart_tx.v
  E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/new/spi_flash_read.v
}
read_ip -quiet E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data.xci
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data_ooc.xdc]

read_ip -quiet E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files E:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top spi_flash_read -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef spi_flash_read.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file spi_flash_read_utilization_synth.rpt -pb spi_flash_read_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
