# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data.xci
# IP: The module: 'uart_rx_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data.xci
# IP: The module: 'uart_rx_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/my_work/A3P250/vivado/RD_FLASH/RD_FLASH.srcs/sources_1/ip/uart_rx_data/uart_rx_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
